name: paypal_sdk
description: PayPal SDK for facilitating integration with PayPal REST APIs
homepage: https://github.com/Omnimind-Ltd/paypal-sdk
version: 1.0.2

environment:
  sdk: '>=2.15.0 <3.0.0'

dependencies:
  json_annotation: ^4.4.0
  http: ^0.13.4
  logging: ^1.0.2

dev_dependencies:
  lints: ^1.0.1
  test: ^1.20.1
  build_runner: ^2.1.7
  json_serializable: ^6.1.4
